### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ncphillips** [paper-games/paper-games#13]
Add a LICENSE.md file with an open source license

**Comment by vchrombie** [comment]
Hello,
I am interested to contribute to this project.

Can I take issue and get started?

**Comment by vchrombie** [comment]
Can you tell me what License should I add?

**Comment by ncphillips** [comment]
hey @vchrombie thanks for the interest. I am going to spend some more time thinking about this before making a decision. See my comment on your PR: https://github.com/paper-games/paper-games/pull/17

**Comment by vchrombie** [comment]
Thats's fine. :)
